// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: maxapi/proto/maxapi.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MaxApiInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input int32 `protobuf:"varint,1,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *MaxApiInput) Reset() {
	*x = MaxApiInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maxapi_proto_maxapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaxApiInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxApiInput) ProtoMessage() {}

func (x *MaxApiInput) ProtoReflect() protoreflect.Message {
	mi := &file_maxapi_proto_maxapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxApiInput.ProtoReflect.Descriptor instead.
func (*MaxApiInput) Descriptor() ([]byte, []int) {
	return file_maxapi_proto_maxapi_proto_rawDescGZIP(), []int{0}
}

func (x *MaxApiInput) GetInput() int32 {
	if x != nil {
		return x.Input
	}
	return 0
}

type MaxApiOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *MaxApiOutput) Reset() {
	*x = MaxApiOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maxapi_proto_maxapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaxApiOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxApiOutput) ProtoMessage() {}

func (x *MaxApiOutput) ProtoReflect() protoreflect.Message {
	mi := &file_maxapi_proto_maxapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxApiOutput.ProtoReflect.Descriptor instead.
func (*MaxApiOutput) Descriptor() ([]byte, []int) {
	return file_maxapi_proto_maxapi_proto_rawDescGZIP(), []int{1}
}

func (x *MaxApiOutput) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_maxapi_proto_maxapi_proto protoreflect.FileDescriptor

var file_maxapi_proto_maxapi_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x61, 0x78, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d,
	0x61, 0x78, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x61, 0x78,
	0x61, 0x70, 0x69, 0x22, 0x23, 0x0a, 0x0b, 0x4d, 0x61, 0x78, 0x41, 0x70, 0x69, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x26, 0x0a, 0x0c, 0x4d, 0x61, 0x78, 0x41,
	0x70, 0x69, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x32, 0x51, 0x0a, 0x10, 0x4d, 0x61, 0x78, 0x41, 0x70, 0x69, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x6f, 0x72, 0x12, 0x3d, 0x0a, 0x0c, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x65, 0x4d, 0x61, 0x78, 0x12, 0x13, 0x2e, 0x6d, 0x61, 0x78, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61,
	0x78, 0x41, 0x70, 0x69, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x14, 0x2e, 0x6d, 0x61, 0x78, 0x61,
	0x70, 0x69, 0x2e, 0x4d, 0x61, 0x78, 0x41, 0x70, 0x69, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x69, 0x6e, 0x61, 0x62, 0x69, 0x6e, 0x61, 0x73, 0x68, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x6d, 0x61, 0x78, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_maxapi_proto_maxapi_proto_rawDescOnce sync.Once
	file_maxapi_proto_maxapi_proto_rawDescData = file_maxapi_proto_maxapi_proto_rawDesc
)

func file_maxapi_proto_maxapi_proto_rawDescGZIP() []byte {
	file_maxapi_proto_maxapi_proto_rawDescOnce.Do(func() {
		file_maxapi_proto_maxapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_maxapi_proto_maxapi_proto_rawDescData)
	})
	return file_maxapi_proto_maxapi_proto_rawDescData
}

var file_maxapi_proto_maxapi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_maxapi_proto_maxapi_proto_goTypes = []any{
	(*MaxApiInput)(nil),  // 0: maxapi.MaxApiInput
	(*MaxApiOutput)(nil), // 1: maxapi.MaxApiOutput
}
var file_maxapi_proto_maxapi_proto_depIdxs = []int32{
	0, // 0: maxapi.MaxApiCalculator.CalculateMax:input_type -> maxapi.MaxApiInput
	1, // 1: maxapi.MaxApiCalculator.CalculateMax:output_type -> maxapi.MaxApiOutput
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_maxapi_proto_maxapi_proto_init() }
func file_maxapi_proto_maxapi_proto_init() {
	if File_maxapi_proto_maxapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_maxapi_proto_maxapi_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MaxApiInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_maxapi_proto_maxapi_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MaxApiOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_maxapi_proto_maxapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_maxapi_proto_maxapi_proto_goTypes,
		DependencyIndexes: file_maxapi_proto_maxapi_proto_depIdxs,
		MessageInfos:      file_maxapi_proto_maxapi_proto_msgTypes,
	}.Build()
	File_maxapi_proto_maxapi_proto = out.File
	file_maxapi_proto_maxapi_proto_rawDesc = nil
	file_maxapi_proto_maxapi_proto_goTypes = nil
	file_maxapi_proto_maxapi_proto_depIdxs = nil
}
