// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: maxapi/proto/maxapi.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MaxApiCalculator_CalculateMax_FullMethodName = "/maxapi.MaxApiCalculator/CalculateMax"
)

// MaxApiCalculatorClient is the client API for MaxApiCalculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MaxApiCalculatorClient interface {
	CalculateMax(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MaxApiInput, MaxApiOutput], error)
}

type maxApiCalculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewMaxApiCalculatorClient(cc grpc.ClientConnInterface) MaxApiCalculatorClient {
	return &maxApiCalculatorClient{cc}
}

func (c *maxApiCalculatorClient) CalculateMax(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MaxApiInput, MaxApiOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MaxApiCalculator_ServiceDesc.Streams[0], MaxApiCalculator_CalculateMax_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MaxApiInput, MaxApiOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MaxApiCalculator_CalculateMaxClient = grpc.BidiStreamingClient[MaxApiInput, MaxApiOutput]

// MaxApiCalculatorServer is the server API for MaxApiCalculator service.
// All implementations must embed UnimplementedMaxApiCalculatorServer
// for forward compatibility.
type MaxApiCalculatorServer interface {
	CalculateMax(grpc.BidiStreamingServer[MaxApiInput, MaxApiOutput]) error
	mustEmbedUnimplementedMaxApiCalculatorServer()
}

// UnimplementedMaxApiCalculatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMaxApiCalculatorServer struct{}

func (UnimplementedMaxApiCalculatorServer) CalculateMax(grpc.BidiStreamingServer[MaxApiInput, MaxApiOutput]) error {
	return status.Errorf(codes.Unimplemented, "method CalculateMax not implemented")
}
func (UnimplementedMaxApiCalculatorServer) mustEmbedUnimplementedMaxApiCalculatorServer() {}
func (UnimplementedMaxApiCalculatorServer) testEmbeddedByValue()                          {}

// UnsafeMaxApiCalculatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MaxApiCalculatorServer will
// result in compilation errors.
type UnsafeMaxApiCalculatorServer interface {
	mustEmbedUnimplementedMaxApiCalculatorServer()
}

func RegisterMaxApiCalculatorServer(s grpc.ServiceRegistrar, srv MaxApiCalculatorServer) {
	// If the following call pancis, it indicates UnimplementedMaxApiCalculatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MaxApiCalculator_ServiceDesc, srv)
}

func _MaxApiCalculator_CalculateMax_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MaxApiCalculatorServer).CalculateMax(&grpc.GenericServerStream[MaxApiInput, MaxApiOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MaxApiCalculator_CalculateMaxServer = grpc.BidiStreamingServer[MaxApiInput, MaxApiOutput]

// MaxApiCalculator_ServiceDesc is the grpc.ServiceDesc for MaxApiCalculator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MaxApiCalculator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "maxapi.MaxApiCalculator",
	HandlerType: (*MaxApiCalculatorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CalculateMax",
			Handler:       _MaxApiCalculator_CalculateMax_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "maxapi/proto/maxapi.proto",
}
