// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: avg/proto/avg.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvgInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input int32 `protobuf:"varint,1,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *AvgInput) Reset() {
	*x = AvgInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_avg_proto_avg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvgInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvgInput) ProtoMessage() {}

func (x *AvgInput) ProtoReflect() protoreflect.Message {
	mi := &file_avg_proto_avg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvgInput.ProtoReflect.Descriptor instead.
func (*AvgInput) Descriptor() ([]byte, []int) {
	return file_avg_proto_avg_proto_rawDescGZIP(), []int{0}
}

func (x *AvgInput) GetInput() int32 {
	if x != nil {
		return x.Input
	}
	return 0
}

type AvgOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result float32 `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AvgOutput) Reset() {
	*x = AvgOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_avg_proto_avg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvgOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvgOutput) ProtoMessage() {}

func (x *AvgOutput) ProtoReflect() protoreflect.Message {
	mi := &file_avg_proto_avg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvgOutput.ProtoReflect.Descriptor instead.
func (*AvgOutput) Descriptor() ([]byte, []int) {
	return file_avg_proto_avg_proto_rawDescGZIP(), []int{1}
}

func (x *AvgOutput) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_avg_proto_avg_proto protoreflect.FileDescriptor

var file_avg_proto_avg_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x76, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x76, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x76, 0x67, 0x22, 0x20, 0x0a, 0x08, 0x41, 0x76,
	0x67, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x23, 0x0a, 0x09,
	0x41, 0x76, 0x67, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x32, 0x40, 0x0a, 0x0d, 0x41, 0x76, 0x67, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x12, 0x2f, 0x0a, 0x0c, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x41,
	0x76, 0x67, 0x12, 0x0d, 0x2e, 0x61, 0x76, 0x67, 0x2e, 0x41, 0x76, 0x67, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x1a, 0x0e, 0x2e, 0x61, 0x76, 0x67, 0x2e, 0x41, 0x76, 0x67, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x28, 0x01, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x69, 0x6e, 0x61, 0x62, 0x69, 0x6e, 0x61, 0x73, 0x68, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x61, 0x76, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_avg_proto_avg_proto_rawDescOnce sync.Once
	file_avg_proto_avg_proto_rawDescData = file_avg_proto_avg_proto_rawDesc
)

func file_avg_proto_avg_proto_rawDescGZIP() []byte {
	file_avg_proto_avg_proto_rawDescOnce.Do(func() {
		file_avg_proto_avg_proto_rawDescData = protoimpl.X.CompressGZIP(file_avg_proto_avg_proto_rawDescData)
	})
	return file_avg_proto_avg_proto_rawDescData
}

var file_avg_proto_avg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_avg_proto_avg_proto_goTypes = []any{
	(*AvgInput)(nil),  // 0: avg.AvgInput
	(*AvgOutput)(nil), // 1: avg.AvgOutput
}
var file_avg_proto_avg_proto_depIdxs = []int32{
	0, // 0: avg.AvgCalculator.CalculateAvg:input_type -> avg.AvgInput
	1, // 1: avg.AvgCalculator.CalculateAvg:output_type -> avg.AvgOutput
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_avg_proto_avg_proto_init() }
func file_avg_proto_avg_proto_init() {
	if File_avg_proto_avg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_avg_proto_avg_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AvgInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_avg_proto_avg_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AvgOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_avg_proto_avg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_avg_proto_avg_proto_goTypes,
		DependencyIndexes: file_avg_proto_avg_proto_depIdxs,
		MessageInfos:      file_avg_proto_avg_proto_msgTypes,
	}.Build()
	File_avg_proto_avg_proto = out.File
	file_avg_proto_avg_proto_rawDesc = nil
	file_avg_proto_avg_proto_goTypes = nil
	file_avg_proto_avg_proto_depIdxs = nil
}
