// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: avg/proto/avg.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AvgCalculator_CalculateAvg_FullMethodName = "/avg.AvgCalculator/CalculateAvg"
)

// AvgCalculatorClient is the client API for AvgCalculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AvgCalculatorClient interface {
	CalculateAvg(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AvgInput, AvgOutput], error)
}

type avgCalculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewAvgCalculatorClient(cc grpc.ClientConnInterface) AvgCalculatorClient {
	return &avgCalculatorClient{cc}
}

func (c *avgCalculatorClient) CalculateAvg(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AvgInput, AvgOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AvgCalculator_ServiceDesc.Streams[0], AvgCalculator_CalculateAvg_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AvgInput, AvgOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AvgCalculator_CalculateAvgClient = grpc.ClientStreamingClient[AvgInput, AvgOutput]

// AvgCalculatorServer is the server API for AvgCalculator service.
// All implementations must embed UnimplementedAvgCalculatorServer
// for forward compatibility.
type AvgCalculatorServer interface {
	CalculateAvg(grpc.ClientStreamingServer[AvgInput, AvgOutput]) error
	mustEmbedUnimplementedAvgCalculatorServer()
}

// UnimplementedAvgCalculatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAvgCalculatorServer struct{}

func (UnimplementedAvgCalculatorServer) CalculateAvg(grpc.ClientStreamingServer[AvgInput, AvgOutput]) error {
	return status.Errorf(codes.Unimplemented, "method CalculateAvg not implemented")
}
func (UnimplementedAvgCalculatorServer) mustEmbedUnimplementedAvgCalculatorServer() {}
func (UnimplementedAvgCalculatorServer) testEmbeddedByValue()                       {}

// UnsafeAvgCalculatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AvgCalculatorServer will
// result in compilation errors.
type UnsafeAvgCalculatorServer interface {
	mustEmbedUnimplementedAvgCalculatorServer()
}

func RegisterAvgCalculatorServer(s grpc.ServiceRegistrar, srv AvgCalculatorServer) {
	// If the following call pancis, it indicates UnimplementedAvgCalculatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AvgCalculator_ServiceDesc, srv)
}

func _AvgCalculator_CalculateAvg_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AvgCalculatorServer).CalculateAvg(&grpc.GenericServerStream[AvgInput, AvgOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AvgCalculator_CalculateAvgServer = grpc.ClientStreamingServer[AvgInput, AvgOutput]

// AvgCalculator_ServiceDesc is the grpc.ServiceDesc for AvgCalculator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AvgCalculator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avg.AvgCalculator",
	HandlerType: (*AvgCalculatorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CalculateAvg",
			Handler:       _AvgCalculator_CalculateAvg_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "avg/proto/avg.proto",
}
