// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: primes/proto/primes.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrimeCalculator_CalculatePrimes_FullMethodName = "/primes.PrimeCalculator/CalculatePrimes"
)

// PrimeCalculatorClient is the client API for PrimeCalculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrimeCalculatorClient interface {
	CalculatePrimes(ctx context.Context, in *PrimeInput, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PrimeOutput], error)
}

type primeCalculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimeCalculatorClient(cc grpc.ClientConnInterface) PrimeCalculatorClient {
	return &primeCalculatorClient{cc}
}

func (c *primeCalculatorClient) CalculatePrimes(ctx context.Context, in *PrimeInput, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PrimeOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PrimeCalculator_ServiceDesc.Streams[0], PrimeCalculator_CalculatePrimes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PrimeInput, PrimeOutput]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PrimeCalculator_CalculatePrimesClient = grpc.ServerStreamingClient[PrimeOutput]

// PrimeCalculatorServer is the server API for PrimeCalculator service.
// All implementations must embed UnimplementedPrimeCalculatorServer
// for forward compatibility.
type PrimeCalculatorServer interface {
	CalculatePrimes(*PrimeInput, grpc.ServerStreamingServer[PrimeOutput]) error
	mustEmbedUnimplementedPrimeCalculatorServer()
}

// UnimplementedPrimeCalculatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrimeCalculatorServer struct{}

func (UnimplementedPrimeCalculatorServer) CalculatePrimes(*PrimeInput, grpc.ServerStreamingServer[PrimeOutput]) error {
	return status.Errorf(codes.Unimplemented, "method CalculatePrimes not implemented")
}
func (UnimplementedPrimeCalculatorServer) mustEmbedUnimplementedPrimeCalculatorServer() {}
func (UnimplementedPrimeCalculatorServer) testEmbeddedByValue()                         {}

// UnsafePrimeCalculatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrimeCalculatorServer will
// result in compilation errors.
type UnsafePrimeCalculatorServer interface {
	mustEmbedUnimplementedPrimeCalculatorServer()
}

func RegisterPrimeCalculatorServer(s grpc.ServiceRegistrar, srv PrimeCalculatorServer) {
	// If the following call pancis, it indicates UnimplementedPrimeCalculatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrimeCalculator_ServiceDesc, srv)
}

func _PrimeCalculator_CalculatePrimes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeInput)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PrimeCalculatorServer).CalculatePrimes(m, &grpc.GenericServerStream[PrimeInput, PrimeOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PrimeCalculator_CalculatePrimesServer = grpc.ServerStreamingServer[PrimeOutput]

// PrimeCalculator_ServiceDesc is the grpc.ServiceDesc for PrimeCalculator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrimeCalculator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "primes.PrimeCalculator",
	HandlerType: (*PrimeCalculatorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CalculatePrimes",
			Handler:       _PrimeCalculator_CalculatePrimes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "primes/proto/primes.proto",
}
